version: '3'
name: gbd
services:
  nginx:
    image: mynginx
    container_name: gbd-nginx
    environment:
    - VIRTUAL_HOST=benchmark-database.de
    secrets:
    - awstats_htpasswd
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ${GBD_ROOT:-/home/iser}/nginx/ssl:/etc/nginx/ssl
    - ${GBD_ROOT:-/home/iser}/nginx/ssl/bot:/etc/nginx/ssl/bot
    - ${GBD_ROOT:-/home/iser}/nginx/awstats:/awstats

  gbd:
    depends_on:
    - nginx
    image: mygbd
    environment:
    - GBD_DB=/raid/gbd/meta.db:/raid/gbd/base.db:/raid/gbd/wcnf_local.db:/raid/gbd/wcnf_meta.db:/raid/gbd/wcnf_base.db:/raid/gbd/opb_local.db:/raid/gbd/opb_meta.db:/raid/gbd/opb_base.db
    ports:
    - 44071:44071
    volumes:
    - ${GBD_ROOT:-/home/iser}/gbd:/raid/gbd:ro
    - ${GBD_ROOT:-/home/iser}/logs:/logs:rw
    restart: always

secrets:
  awstats_htpasswd:
    file: ${GBD_ROOT:-/home/iser}/nginx/secrets/awstats.htpasswd
